#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1321006069.723517
__CHEETAH_genTimestamp__ = 'Fri Nov 11 23:07:49 2011'
__CHEETAH_src__ = 'user_resource_grant.tmpl'
__CHEETAH_srcLastModified__ = 'Fri Nov 11 19:31:22 2011'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class user_resource_grant(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(user_resource_grant, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>''')
        _v = VFFSL(SL,"title",True) # u'$title' on line 7, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'$title')) # from line 7, col 12.
        write(u'''</title>
    
  </head>
  <body>
    <div id="content">
      
      <form id="grant_form" method="post" action="''')
        _v = VFFSL(SL,"action",True) # u'$action' on line 13, col 51
        if _v is not None: write(_filter(_v, rawExpr=u'$action')) # from line 13, col 51.
        write(u'''">
        <fieldset class="grant_field">
          <legend>Resource grant?</legend>
          <div>''')
        _v = VFFSL(SL,"message",True) # u'$message' on line 16, col 16
        if _v is not None: write(_filter(_v, rawExpr=u'$message')) # from line 16, col 16.
        write(u'''</div>
          <input type="submit" name="allow" value="Allow"/>
          <input type="submit" name="deny" value="Deny"/>
          <input type="hidden" name="user_id" value="''')
        _v = VFFSL(SL,"user_id",True) # u'$user_id' on line 19, col 54
        if _v is not None: write(_filter(_v, rawExpr=u'$user_id')) # from line 19, col 54.
        write(u'''"/>
          <input type="hidden" name="client_id" value="''')
        _v = VFFSL(SL,"client_id",True) # u'$client_id' on line 20, col 56
        if _v is not None: write(_filter(_v, rawExpr=u'$client_id')) # from line 20, col 56.
        write(u'''"/>
          <input type="hidden" name="redirect_uri"
          value="''')
        _v = VFFSL(SL,"redirect_uri",True) # u'$redirect_uri' on line 22, col 18
        if _v is not None: write(_filter(_v, rawExpr=u'$redirect_uri')) # from line 22, col 18.
        write(u'''"/>
''')
        if VFFSL(SL,"scope",True): # generated from line 23, col 11
            write(u'''          <input type="hidden" name="scope" value="''')
            _v = VFFSL(SL,"scope",True) # u'$scope' on line 24, col 52
            if _v is not None: write(_filter(_v, rawExpr=u'$scope')) # from line 24, col 52.
            write(u'''"/>
''')
        if VFFSL(SL,"state",True): # generated from line 26, col 11
            write(u'''          <input type="hidden" name="state" value="''')
            _v = VFFSL(SL,"state",True) # u'$state' on line 27, col 52
            if _v is not None: write(_filter(_v, rawExpr=u'$state')) # from line 27, col 52.
            write(u'''"/>
''')
        if VFFSL(SL,"token",True): # generated from line 29, col 11
            write(u'''          <input type="hidden" name="token" value="token"/>
''')
        write(u'''        </fieldset>
      </form>
    </div>
  </body>
</html>
  
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_user_resource_grant= 'respond'

## END CLASS DEFINITION

if not hasattr(user_resource_grant, '_initCheetahAttributes'):
    templateAPIClass = getattr(user_resource_grant, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(user_resource_grant)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=user_resource_grant()).run()


